CREATE TABLE IF NOT EXISTS NOBEL_WIN(
    YEARR INTEGER,
    SUBJECTS TEXT,
    WINNER TEXT,
    COUNTRY TEXT,
    CATAERGORY TEXT
);

INSERT INTO NOBEL_WIN (YEARR, SUBJECTS, WINNER, COUNTRY, CATAERGORY) VALUES
(1970, 'PHYSICS', 'HANNES', 'SWEDEN', 'SCIENTIST'),
(1980, 'ENGLISH', 'ANNIE', 'USA', 'ECONOMIST'),
(1990, 'MATHS', 'KELVIN', 'SWEDEN', 'LINGUIST'),
(2000, 'GEOGRAPHY', 'DAVE', 'CANADA', 'PRIME MINISTER'),
(1964, 'PHYSICS', 'JONNY', 'USA', 'SCIENTIST'),
(1970, 'ENGLISH', 'PETER', 'SWEDEN', 'PRESIDENT'),
(2001, 'HISTORY', 'HAMILTON', 'SWEDEN', 'LINGUIST'),
(1985, 'MATHS', 'PHILIPS', 'SWEDEN', 'ECONOMIST'),
(1976, 'GEOGRAPHY', 'HANNAH', 'SWEDEN', 'SCIENTIST'),
(1991, 'PHYSICS', 'LOUIS', 'SWEDEN', 'JOURNALIST');

SELECT * FROM NOBEL_WIN
WHERE SUBJECTS NOT LIKE 'P%';